[package]
name = "bench-build"
version = "0.0.0"
authors = ["askama-rs developers"]
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
askama = { package = "stoneware", path = "../askama", default-features = false, features = ["std"] }
askama_macros = { package = "stoneware-macros", path = "../askama_macros", features = ["std"] }

[features]
default = []
derive = ["askama/derive"]

[workspace]
members = ["."]
